name: build package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-rpm:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    container:
      image: "oceanbase/obdiag-builder:latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export PATH=/opt/miniconda3/bin:$PATH
          source activate obdiag
          ldd --version
          pip3 install -r requirements3.txt

      - name: Build package
        run: |
          export PATH=/opt/miniconda3/bin:$PATH
          source activate obdiag
          pwd
          ls -lh
          export RELEASE=`date +%Y%m%d%H%M`
          sed -i 's/pip install -r requirements3.txt/curl https:\/\/bootstrap.pypa.io\/get-pip.py -o get-pip.py\n\
          python3 get-pip.py\n\
          pip3 install -r requirements3.txt/' ./rpm/oceanbase-diagnostic-tool.spec
          python3 -m pip install --upgrade pip wheel
          cat ./rpm/oceanbase-diagnostic-tool.spec
          python3 --version
          rpmbuild -bb ./rpm/oceanbase-diagnostic-tool.spec

      - name: Find rpm
        run: |
          find / -name oceanbase-diagnostic-tool-*.rpm

      - name: "Upload rpm"
        uses: actions/upload-artifact@v3
        with:
          name: obdiag-rpm-packages
          path: |
            /github/home/rpmbuild/RPMS/x86_64/oceanbase-diagnostic-tool-*.rpm
          retention-days: 3
          debug: true

  convert-to-deb:
    needs: build-rpm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: debian-11
            image: debian:11
            artifact_name: obdiag-deb-package-debian11
          - distro: ubuntu-22.04
            image: ubuntu:22.04
            artifact_name: obdiag-deb-package-ubuntu2204

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download RPM Artifact
        uses: actions/download-artifact@v3
        with:
          name: obdiag-rpm-packages
          path: .

      - name: Update and Install Dependencies
        run: |
          apt-get update && apt-get install -y \
            alien \
            dpkg-dev \
            rpm2cpio \
            cpio \
            fakeroot

      - name: Convert RPM to DEB
        run: |
          ls -lh oceanbase-diagnostic-tool-*.rpm
          sudo alien -k --scripts oceanbase-diagnostic-tool-*.rpm
          ls -lh ./oceanbase-diagnostic-tool_*.deb

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ./oceanbase-diagnostic-tool_*.deb
          retention-days: 3