name: build rpm

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*"

jobs:
  build-and-package-x86_64:
    runs-on: ubuntu-22.04
    container: centos:7.9.2009

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (From Source)
        run: |
          yum install -y gcc make openssl-devel zlib-devel bzip2-devel libffi-devel wget
          wget https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tgz
          tar xvf Python-3.8.18.tgz
          cd Python-3.8.18
          ./configure --enable-optimizations
          make altinstall
          python3.8 --version
          ln -sf /usr/local/bin/python3.8 /usr/local/bin/python3

      - name: Install dependencies
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          pip3 install -r requirements3.txt

      - name: Set up build env
        run: |
          yum install gcc make
          yum install fakeroot

      - name: Build package
        run: |
          pwd
          ls -lh
          export RELEASE=`date +%Y%m%d%H%M`
          cat ./rpm/oceanbase-diagnostic-tool.spec
          rpmbuild -bb ./rpm/oceanbase-diagnostic-tool.spec

      - name: Convert RPM to DEB
        run: |
          mkdir -p /home/runner/artifacts
          fakeroot alien --scripts --to-deb /home/runner/rpmbuild/RPMS/x86_64/oceanbase-diagnostic-tool-*.rpm

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: obdiag-packages
          path: |
            /home/runner/rpmbuild/RPMS/x86_64/oceanbase-diagnostic-tool-*.rpm
            /home/runner/work/obdiag/obdiag/oceanbase-diagnostic-tool_*.deb
          retention-days: 3
          debug: true